#%RAML 1.0
title: Agents API
version: 1.0
types:
  Agent:
    type: object
    properties:
      name:
        type: string
      agentType:
        type: string
        enum:
          - Person
          - Organization

/agents:
  get:
    responses:
      200:
        body:
          application/json:
            type: Agent[]
            example:
              - name: Polimi
                agentType: Organization
              - name: Nicolas
                agentType: Person