PREFIX documentation: <http://a.ml/vocabularies/documentation#>
ASK {
    FILTER NOT EXISTS {?s a documentation:Documentable
                       FILTER NOT EXISTS {
                                         ?s a documentation:Documented
                                         }
                      }

    }
