PREFIX documentation: <http://a.ml/vocabularies/documentation#>
PREFIX dsm: <http://a.ml/vocabularies/document-source-maps#>
SELECT ?id ?lexical_data
WHERE {
      ?id a documentation:Documentable
      FILTER NOT EXISTS {
                        ?id a documentation:Documented
                        }
      OPTIONAL {
               ?id dsm:sources/dsm:lexical ?lexicalNode .
               ?lexicalNode dsm:element ?graph_element ;
                            dsm:value ?lexical_data .
               FILTER (STRAFTER(STR(?graph_element), "#") = STRAFTER(STR(?id), "#") )
               }
      }