PREFIX security: <http://a.ml/vocabularies/security#>
CONSTRUCT {
          ?this a security:Secure .
          }
WHERE {
      ?this a security:Securable;
            security:securityTransferProperty ?object .
      ?object a security:Secure .
      }
GROUP BY ?this
