PREFIX documentation: <http://a.ml/vocabularies/documentation#>
SELECT ?documented ?total
WHERE {
      {
      SELECT(COUNT(?documentable) as ?total)
      WHERE {
            ?documentable a documentation:Documentable .
            }
      }
      {
      SELECT(COUNT(?documented_) as ?documented)
      WHERE {
            ?documented_ a documentation:Documented .
            }
      }
      }

