PREFIX documentation: <file://src/main/resources/web-apis/ontologies/documentation#>
SELECT ?totalDocumented ?total
WHERE {
      {
      SELECT(COUNT(?documentable) as ?total)
      WHERE {
            ?documentable a documentation:Documentable .
            }
      }
      {
      SELECT(COUNT(?documented) as ?totalDocumented)
      WHERE {
            ?documented a documentation:Documented .
            }

      }
      }

