PREFIX documentation: <file://src/main/resources/web-apis/ontologies/documentation#>
ASK {
    FILTER NOT EXISTS {?s a documentation:Documentable
                       FILTER NOT EXISTS {
                                         ?s a documentation:Documented
                                         }
                      }

    }
