PREFIX security: <http://a.ml/vocabularies/security#>
SELECT ?id
WHERE {
      ?id a security:Securable
      FILTER NOT EXISTS {
                        ?id a security:Secured
                        }
      }